{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3bcbea47",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "96e455ed",
   "metadata": {},
   "outputs": [],
   "source": [
    "df= pd.read_excel('sample_data.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a0a2c388",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>Conductor Material</td>\n",
       "      <td>Stranded bare copper ( DIN VDE 0295 Class 5 / ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>Insulation Material &amp; \\nColor</td>\n",
       "      <td>Polypropylene, DIN VDE 0293‐1 ( color )  \\nA) ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>Braid Armor Material</td>\n",
       "      <td>Tinned Copper Braid Shield</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>Inner / Out Jacket \\nMaterial</td>\n",
       "      <td>LSZH ( Low Smoke Zero Halogen )</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>5</td>\n",
       "      <td>Flame Retardancy</td>\n",
       "      <td>VDE 0482‐332‐1‐2, DIN EN 60332‐1‐2, IEC 60332‐1‐2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>5</td>\n",
       "      <td>6</td>\n",
       "      <td>Oil Resistant</td>\n",
       "      <td>70°C x 4h ( IEC 60811 )</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>6</td>\n",
       "      <td>7</td>\n",
       "      <td>Voltage Rating (U0/U)</td>\n",
       "      <td>300 / 500 V</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>7</td>\n",
       "      <td>8</td>\n",
       "      <td>Temperature Range</td>\n",
       "      <td>‐30°C to +70°C ( Occasional movement )  \\n‐40°...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>8</td>\n",
       "      <td>9</td>\n",
       "      <td>Bending Radius</td>\n",
       "      <td>20 x OD ( Occasional movement ) \\n6 x OD ( Fix...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>9</td>\n",
       "      <td>10</td>\n",
       "      <td>Test Voltage</td>\n",
       "      <td>4000 V</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>10</td>\n",
       "      <td>11</td>\n",
       "      <td>Smoke/ Halogen \\nProperties</td>\n",
       "      <td>IEC 61034-2, IEC 60754-1, IEC 60754-2, VDE 048...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>11</td>\n",
       "      <td>12</td>\n",
       "      <td>Other Properties</td>\n",
       "      <td>Good UV resistance, chemical resistance &amp; flex...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Unnamed: 0   0                              1  \\\n",
       "0            0   1             Conductor Material   \n",
       "1            1   2  Insulation Material & \\nColor   \n",
       "2            2   3           Braid Armor Material   \n",
       "3            3   4  Inner / Out Jacket \\nMaterial   \n",
       "4            4   5               Flame Retardancy   \n",
       "5            5   6                  Oil Resistant   \n",
       "6            6   7          Voltage Rating (U0/U)   \n",
       "7            7   8              Temperature Range   \n",
       "8            8   9                 Bending Radius   \n",
       "9            9  10                   Test Voltage   \n",
       "10          10  11    Smoke/ Halogen \\nProperties   \n",
       "11          11  12               Other Properties   \n",
       "\n",
       "                                                    2  \n",
       "0   Stranded bare copper ( DIN VDE 0295 Class 5 / ...  \n",
       "1   Polypropylene, DIN VDE 0293‐1 ( color )  \\nA) ...  \n",
       "2                          Tinned Copper Braid Shield  \n",
       "3                     LSZH ( Low Smoke Zero Halogen )  \n",
       "4   VDE 0482‐332‐1‐2, DIN EN 60332‐1‐2, IEC 60332‐1‐2  \n",
       "5                             70°C x 4h ( IEC 60811 )  \n",
       "6                                         300 / 500 V  \n",
       "7   ‐30°C to +70°C ( Occasional movement )  \\n‐40°...  \n",
       "8   20 x OD ( Occasional movement ) \\n6 x OD ( Fix...  \n",
       "9                                              4000 V  \n",
       "10  IEC 61034-2, IEC 60754-1, IEC 60754-2, VDE 048...  \n",
       "11  Good UV resistance, chemical resistance & flex...  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3ee351fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "list1=list(df[1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e0e75b77",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Conductor Material', 'Insulation Material & \\nColor', 'Braid Armor Material', 'Inner / Out Jacket \\nMaterial', 'Flame Retardancy', 'Oil Resistant', 'Voltage Rating (U0/U)', 'Temperature Range', 'Bending Radius', 'Test Voltage', 'Smoke/ Halogen \\nProperties', 'Other Properties']\n"
     ]
    }
   ],
   "source": [
    "print(list1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "9cd1bea8",
   "metadata": {},
   "outputs": [],
   "source": [
    "df1= pd.read_excel('sample_data.xlsx',sheet_name=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6df4d2a0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>Part Code</td>\n",
       "      <td>Cable \\nDescription</td>\n",
       "      <td>No. of \\nCores</td>\n",
       "      <td>Nom. Conductor \\nSize (mm²)</td>\n",
       "      <td>Nom. Cable \\nDiameter (mm)</td>\n",
       "      <td>Nom. Cable \\nWeight (kg/km)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>2X0.5CH</td>\n",
       "      <td>2 X0.5</td>\n",
       "      <td>2</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.1</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>3X0.5CH</td>\n",
       "      <td>3 X0.5</td>\n",
       "      <td>3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.4</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>3G0.5CH</td>\n",
       "      <td>3 G0.5</td>\n",
       "      <td>3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.4</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>4X0.5CH</td>\n",
       "      <td>4 X0.5</td>\n",
       "      <td>4</td>\n",
       "      <td>0.5</td>\n",
       "      <td>8.0</td>\n",
       "      <td>91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>5</td>\n",
       "      <td>4G0.5CH</td>\n",
       "      <td>4 G0.5</td>\n",
       "      <td>4</td>\n",
       "      <td>0.5</td>\n",
       "      <td>8.0</td>\n",
       "      <td>91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>6</td>\n",
       "      <td>5X0.5CH</td>\n",
       "      <td>5 X0.5</td>\n",
       "      <td>5</td>\n",
       "      <td>0.5</td>\n",
       "      <td>8.6</td>\n",
       "      <td>102</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>7</td>\n",
       "      <td>5G0.5CH</td>\n",
       "      <td>5 G0.5</td>\n",
       "      <td>5</td>\n",
       "      <td>0.5</td>\n",
       "      <td>8.6</td>\n",
       "      <td>102</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>8</td>\n",
       "      <td>6G0.5CH</td>\n",
       "      <td>6 G0.5</td>\n",
       "      <td>6</td>\n",
       "      <td>0.5</td>\n",
       "      <td>9.4</td>\n",
       "      <td>132</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>9</td>\n",
       "      <td>7X0.5CH</td>\n",
       "      <td>7 X0.5</td>\n",
       "      <td>7</td>\n",
       "      <td>0.5</td>\n",
       "      <td>9.4</td>\n",
       "      <td>140</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>10</td>\n",
       "      <td>7G0.5CH</td>\n",
       "      <td>7 G0.5</td>\n",
       "      <td>7</td>\n",
       "      <td>0.5</td>\n",
       "      <td>9.4</td>\n",
       "      <td>140</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>11</td>\n",
       "      <td>9X0.5CH</td>\n",
       "      <td>9 X0.5</td>\n",
       "      <td>9</td>\n",
       "      <td>0.5</td>\n",
       "      <td>11.3</td>\n",
       "      <td>173</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>12</td>\n",
       "      <td>9G0.5CH</td>\n",
       "      <td>9 G0.5</td>\n",
       "      <td>9</td>\n",
       "      <td>0.5</td>\n",
       "      <td>11.3</td>\n",
       "      <td>173</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>13</td>\n",
       "      <td>10X0.5CH</td>\n",
       "      <td>10 X0.5</td>\n",
       "      <td>10</td>\n",
       "      <td>0.5</td>\n",
       "      <td>11.7</td>\n",
       "      <td>179</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>14</td>\n",
       "      <td>10G0.5CH</td>\n",
       "      <td>10 G0.5</td>\n",
       "      <td>10</td>\n",
       "      <td>0.5</td>\n",
       "      <td>11.7</td>\n",
       "      <td>179</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>15</td>\n",
       "      <td>12X0.5CH</td>\n",
       "      <td>12 X0.5</td>\n",
       "      <td>12</td>\n",
       "      <td>0.5</td>\n",
       "      <td>12.0</td>\n",
       "      <td>205</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>16</td>\n",
       "      <td>12G0.5CH</td>\n",
       "      <td>12 G0.5</td>\n",
       "      <td>12</td>\n",
       "      <td>0.5</td>\n",
       "      <td>12.0</td>\n",
       "      <td>205</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>17</td>\n",
       "      <td>14X0.5CH</td>\n",
       "      <td>14 X0.5</td>\n",
       "      <td>14</td>\n",
       "      <td>0.5</td>\n",
       "      <td>12.7</td>\n",
       "      <td>214</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>18</td>\n",
       "      <td>14G0.5CH</td>\n",
       "      <td>14 G0.5</td>\n",
       "      <td>14</td>\n",
       "      <td>0.5</td>\n",
       "      <td>12.7</td>\n",
       "      <td>214</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>19</td>\n",
       "      <td>16X0.5CH</td>\n",
       "      <td>16 X0.5</td>\n",
       "      <td>16</td>\n",
       "      <td>0.5</td>\n",
       "      <td>13.1</td>\n",
       "      <td>237</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>20</td>\n",
       "      <td>16G0.5CH</td>\n",
       "      <td>16 G0.5</td>\n",
       "      <td>16</td>\n",
       "      <td>0.5</td>\n",
       "      <td>13.1</td>\n",
       "      <td>237</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>21</td>\n",
       "      <td>18X0.5CH</td>\n",
       "      <td>18 X0.5</td>\n",
       "      <td>18</td>\n",
       "      <td>0.5</td>\n",
       "      <td>13.7</td>\n",
       "      <td>271</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>22</td>\n",
       "      <td>18G0.5CH</td>\n",
       "      <td>18 G0.5</td>\n",
       "      <td>18</td>\n",
       "      <td>0.5</td>\n",
       "      <td>13.7</td>\n",
       "      <td>271</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>23</td>\n",
       "      <td>20X0.5CH</td>\n",
       "      <td>20 X0.5</td>\n",
       "      <td>20</td>\n",
       "      <td>0.5</td>\n",
       "      <td>14.4</td>\n",
       "      <td>293</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>24</td>\n",
       "      <td>20G0.5CH</td>\n",
       "      <td>20 G0.5</td>\n",
       "      <td>20</td>\n",
       "      <td>0.5</td>\n",
       "      <td>14.4</td>\n",
       "      <td>293</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>25</td>\n",
       "      <td>2X0.75CH</td>\n",
       "      <td>2 X0.75</td>\n",
       "      <td>2</td>\n",
       "      <td>0.75</td>\n",
       "      <td>7.6</td>\n",
       "      <td>82</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>26</td>\n",
       "      <td>3X0.75CH</td>\n",
       "      <td>3 X0.75</td>\n",
       "      <td>3</td>\n",
       "      <td>0.75</td>\n",
       "      <td>8.0</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>27</td>\n",
       "      <td>3G0.75CH</td>\n",
       "      <td>3 G0.75</td>\n",
       "      <td>3</td>\n",
       "      <td>0.75</td>\n",
       "      <td>8.0</td>\n",
       "      <td>93</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>28</td>\n",
       "      <td>4X0.75CH</td>\n",
       "      <td>4 X0.75</td>\n",
       "      <td>4</td>\n",
       "      <td>0.75</td>\n",
       "      <td>8.6</td>\n",
       "      <td>109</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>29</td>\n",
       "      <td>4G0.75CH</td>\n",
       "      <td>4 G0.75</td>\n",
       "      <td>4</td>\n",
       "      <td>0.75</td>\n",
       "      <td>8.6</td>\n",
       "      <td>109</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>30</td>\n",
       "      <td>5X0.75CH</td>\n",
       "      <td>5 X0.75</td>\n",
       "      <td>5</td>\n",
       "      <td>0.75</td>\n",
       "      <td>9.5</td>\n",
       "      <td>138</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>31</td>\n",
       "      <td>5G0.75CH</td>\n",
       "      <td>5 G0.75</td>\n",
       "      <td>5</td>\n",
       "      <td>0.75</td>\n",
       "      <td>9.5</td>\n",
       "      <td>138</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>32</td>\n",
       "      <td>6G0.75CH</td>\n",
       "      <td>6 G0.75</td>\n",
       "      <td>6</td>\n",
       "      <td>0.75</td>\n",
       "      <td>10.1</td>\n",
       "      <td>159</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>33</td>\n",
       "      <td>7X0.75CH</td>\n",
       "      <td>7 X0.75</td>\n",
       "      <td>7</td>\n",
       "      <td>0.75</td>\n",
       "      <td>10.1</td>\n",
       "      <td>163</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>34</td>\n",
       "      <td>7G0.75CH</td>\n",
       "      <td>7 G0.75</td>\n",
       "      <td>7</td>\n",
       "      <td>0.75</td>\n",
       "      <td>10.1</td>\n",
       "      <td>163</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>35</td>\n",
       "      <td>9X0.75CH</td>\n",
       "      <td>9 X0.75</td>\n",
       "      <td>9</td>\n",
       "      <td>0.75</td>\n",
       "      <td>12.1</td>\n",
       "      <td>204</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>36</td>\n",
       "      <td>9G0.75CH</td>\n",
       "      <td>9 G0.75</td>\n",
       "      <td>9</td>\n",
       "      <td>0.75</td>\n",
       "      <td>12.1</td>\n",
       "      <td>204</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>37</td>\n",
       "      <td>10X0.75CH</td>\n",
       "      <td>10 X0.75</td>\n",
       "      <td>10</td>\n",
       "      <td>0.75</td>\n",
       "      <td>12.6</td>\n",
       "      <td>241</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>38</td>\n",
       "      <td>10G0.75CH</td>\n",
       "      <td>10 G0.75</td>\n",
       "      <td>10</td>\n",
       "      <td>0.75</td>\n",
       "      <td>12.6</td>\n",
       "      <td>241</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>39</td>\n",
       "      <td>12X0.75CH</td>\n",
       "      <td>12 X0.75</td>\n",
       "      <td>12</td>\n",
       "      <td>0.75</td>\n",
       "      <td>13.0</td>\n",
       "      <td>252</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>40</td>\n",
       "      <td>12G0.75CH</td>\n",
       "      <td>12 G0.75</td>\n",
       "      <td>12</td>\n",
       "      <td>0.75</td>\n",
       "      <td>13.0</td>\n",
       "      <td>252</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>41</td>\n",
       "      <td>13G0.75CH</td>\n",
       "      <td>13 G0.75</td>\n",
       "      <td>13</td>\n",
       "      <td>0.75</td>\n",
       "      <td>13.6</td>\n",
       "      <td>273</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>42</td>\n",
       "      <td>14X0.75CH</td>\n",
       "      <td>14 X0.75</td>\n",
       "      <td>14</td>\n",
       "      <td>0.75</td>\n",
       "      <td>13.6</td>\n",
       "      <td>280</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>43</td>\n",
       "      <td>14G0.75CH</td>\n",
       "      <td>14 G0.75</td>\n",
       "      <td>14</td>\n",
       "      <td>0.75</td>\n",
       "      <td>13.6</td>\n",
       "      <td>280</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>44</td>\n",
       "      <td>16X0.75CH</td>\n",
       "      <td>16 X0.75</td>\n",
       "      <td>16</td>\n",
       "      <td>0.75</td>\n",
       "      <td>14.2</td>\n",
       "      <td>299</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>45</td>\n",
       "      <td>16G0.75CH</td>\n",
       "      <td>16 G0.75</td>\n",
       "      <td>16</td>\n",
       "      <td>0.75</td>\n",
       "      <td>14.2</td>\n",
       "      <td>299</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Unnamed: 0          0                    1               2  \\\n",
       "0            0  Part Code  Cable \\nDescription  No. of \\nCores   \n",
       "1            1    2X0.5CH               2 X0.5               2   \n",
       "2            2    3X0.5CH               3 X0.5               3   \n",
       "3            3    3G0.5CH               3 G0.5               3   \n",
       "4            4    4X0.5CH               4 X0.5               4   \n",
       "5            5    4G0.5CH               4 G0.5               4   \n",
       "6            6    5X0.5CH               5 X0.5               5   \n",
       "7            7    5G0.5CH               5 G0.5               5   \n",
       "8            8    6G0.5CH               6 G0.5               6   \n",
       "9            9    7X0.5CH               7 X0.5               7   \n",
       "10          10    7G0.5CH               7 G0.5               7   \n",
       "11          11    9X0.5CH               9 X0.5               9   \n",
       "12          12    9G0.5CH               9 G0.5               9   \n",
       "13          13   10X0.5CH              10 X0.5              10   \n",
       "14          14   10G0.5CH              10 G0.5              10   \n",
       "15          15   12X0.5CH              12 X0.5              12   \n",
       "16          16   12G0.5CH              12 G0.5              12   \n",
       "17          17   14X0.5CH              14 X0.5              14   \n",
       "18          18   14G0.5CH              14 G0.5              14   \n",
       "19          19   16X0.5CH              16 X0.5              16   \n",
       "20          20   16G0.5CH              16 G0.5              16   \n",
       "21          21   18X0.5CH              18 X0.5              18   \n",
       "22          22   18G0.5CH              18 G0.5              18   \n",
       "23          23   20X0.5CH              20 X0.5              20   \n",
       "24          24   20G0.5CH              20 G0.5              20   \n",
       "25          25   2X0.75CH              2 X0.75               2   \n",
       "26          26   3X0.75CH              3 X0.75               3   \n",
       "27          27   3G0.75CH              3 G0.75               3   \n",
       "28          28   4X0.75CH              4 X0.75               4   \n",
       "29          29   4G0.75CH              4 G0.75               4   \n",
       "30          30   5X0.75CH              5 X0.75               5   \n",
       "31          31   5G0.75CH              5 G0.75               5   \n",
       "32          32   6G0.75CH              6 G0.75               6   \n",
       "33          33   7X0.75CH              7 X0.75               7   \n",
       "34          34   7G0.75CH              7 G0.75               7   \n",
       "35          35   9X0.75CH              9 X0.75               9   \n",
       "36          36   9G0.75CH              9 G0.75               9   \n",
       "37          37  10X0.75CH             10 X0.75              10   \n",
       "38          38  10G0.75CH             10 G0.75              10   \n",
       "39          39  12X0.75CH             12 X0.75              12   \n",
       "40          40  12G0.75CH             12 G0.75              12   \n",
       "41          41  13G0.75CH             13 G0.75              13   \n",
       "42          42  14X0.75CH             14 X0.75              14   \n",
       "43          43  14G0.75CH             14 G0.75              14   \n",
       "44          44  16X0.75CH             16 X0.75              16   \n",
       "45          45  16G0.75CH             16 G0.75              16   \n",
       "\n",
       "                              3                           4  \\\n",
       "0   Nom. Conductor \\nSize (mm²)  Nom. Cable \\nDiameter (mm)   \n",
       "1                           0.5                         7.1   \n",
       "2                           0.5                         7.4   \n",
       "3                           0.5                         7.4   \n",
       "4                           0.5                         8.0   \n",
       "5                           0.5                         8.0   \n",
       "6                           0.5                         8.6   \n",
       "7                           0.5                         8.6   \n",
       "8                           0.5                         9.4   \n",
       "9                           0.5                         9.4   \n",
       "10                          0.5                         9.4   \n",
       "11                          0.5                        11.3   \n",
       "12                          0.5                        11.3   \n",
       "13                          0.5                        11.7   \n",
       "14                          0.5                        11.7   \n",
       "15                          0.5                        12.0   \n",
       "16                          0.5                        12.0   \n",
       "17                          0.5                        12.7   \n",
       "18                          0.5                        12.7   \n",
       "19                          0.5                        13.1   \n",
       "20                          0.5                        13.1   \n",
       "21                          0.5                        13.7   \n",
       "22                          0.5                        13.7   \n",
       "23                          0.5                        14.4   \n",
       "24                          0.5                        14.4   \n",
       "25                         0.75                         7.6   \n",
       "26                         0.75                         8.0   \n",
       "27                         0.75                         8.0   \n",
       "28                         0.75                         8.6   \n",
       "29                         0.75                         8.6   \n",
       "30                         0.75                         9.5   \n",
       "31                         0.75                         9.5   \n",
       "32                         0.75                        10.1   \n",
       "33                         0.75                        10.1   \n",
       "34                         0.75                        10.1   \n",
       "35                         0.75                        12.1   \n",
       "36                         0.75                        12.1   \n",
       "37                         0.75                        12.6   \n",
       "38                         0.75                        12.6   \n",
       "39                         0.75                        13.0   \n",
       "40                         0.75                        13.0   \n",
       "41                         0.75                        13.6   \n",
       "42                         0.75                        13.6   \n",
       "43                         0.75                        13.6   \n",
       "44                         0.75                        14.2   \n",
       "45                         0.75                        14.2   \n",
       "\n",
       "                              5  \n",
       "0   Nom. Cable \\nWeight (kg/km)  \n",
       "1                            68  \n",
       "2                            76  \n",
       "3                            76  \n",
       "4                            91  \n",
       "5                            91  \n",
       "6                           102  \n",
       "7                           102  \n",
       "8                           132  \n",
       "9                           140  \n",
       "10                          140  \n",
       "11                          173  \n",
       "12                          173  \n",
       "13                          179  \n",
       "14                          179  \n",
       "15                          205  \n",
       "16                          205  \n",
       "17                          214  \n",
       "18                          214  \n",
       "19                          237  \n",
       "20                          237  \n",
       "21                          271  \n",
       "22                          271  \n",
       "23                          293  \n",
       "24                          293  \n",
       "25                           82  \n",
       "26                           93  \n",
       "27                           93  \n",
       "28                          109  \n",
       "29                          109  \n",
       "30                          138  \n",
       "31                          138  \n",
       "32                          159  \n",
       "33                          163  \n",
       "34                          163  \n",
       "35                          204  \n",
       "36                          204  \n",
       "37                          241  \n",
       "38                          241  \n",
       "39                          252  \n",
       "40                          252  \n",
       "41                          273  \n",
       "42                          280  \n",
       "43                          280  \n",
       "44                          299  \n",
       "45                          299  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "5f8d1cb1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>Part Code</td>\n",
       "      <td>Cable \\nDescription</td>\n",
       "      <td>No. of \\nCores</td>\n",
       "      <td>Nom. Conductor \\nSize (mm²)</td>\n",
       "      <td>Nom. Cable \\nDiameter (mm)</td>\n",
       "      <td>Nom. Cable \\nWeight (kg/km)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>2X0.5CH</td>\n",
       "      <td>2 X0.5</td>\n",
       "      <td>2</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.1</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>3X0.5CH</td>\n",
       "      <td>3 X0.5</td>\n",
       "      <td>3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.4</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>3G0.5CH</td>\n",
       "      <td>3 G0.5</td>\n",
       "      <td>3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.4</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>4X0.5CH</td>\n",
       "      <td>4 X0.5</td>\n",
       "      <td>4</td>\n",
       "      <td>0.5</td>\n",
       "      <td>8.0</td>\n",
       "      <td>91</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Unnamed: 0          0                    1               2  \\\n",
       "0           0  Part Code  Cable \\nDescription  No. of \\nCores   \n",
       "1           1    2X0.5CH               2 X0.5               2   \n",
       "2           2    3X0.5CH               3 X0.5               3   \n",
       "3           3    3G0.5CH               3 G0.5               3   \n",
       "4           4    4X0.5CH               4 X0.5               4   \n",
       "\n",
       "                             3                           4  \\\n",
       "0  Nom. Conductor \\nSize (mm²)  Nom. Cable \\nDiameter (mm)   \n",
       "1                          0.5                         7.1   \n",
       "2                          0.5                         7.4   \n",
       "3                          0.5                         7.4   \n",
       "4                          0.5                         8.0   \n",
       "\n",
       "                             5  \n",
       "0  Nom. Cable \\nWeight (kg/km)  \n",
       "1                           68  \n",
       "2                           76  \n",
       "3                           76  \n",
       "4                           91  "
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df1.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "659e9084",
   "metadata": {},
   "outputs": [],
   "source": [
    "df1.columns=list(\"ABCDEFG\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "381d1c5f",
   "metadata": {},
   "outputs": [],
   "source": [
    "newdf=df1.drop([\"A\"],axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "70c2004b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>B</th>\n",
       "      <th>C</th>\n",
       "      <th>D</th>\n",
       "      <th>E</th>\n",
       "      <th>F</th>\n",
       "      <th>G</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Part Code</td>\n",
       "      <td>Cable \\nDescription</td>\n",
       "      <td>No. of \\nCores</td>\n",
       "      <td>Nom. Conductor \\nSize (mm²)</td>\n",
       "      <td>Nom. Cable \\nDiameter (mm)</td>\n",
       "      <td>Nom. Cable \\nWeight (kg/km)</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2X0.5CH</td>\n",
       "      <td>2 X0.5</td>\n",
       "      <td>2</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.1</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3X0.5CH</td>\n",
       "      <td>3 X0.5</td>\n",
       "      <td>3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.4</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3G0.5CH</td>\n",
       "      <td>3 G0.5</td>\n",
       "      <td>3</td>\n",
       "      <td>0.5</td>\n",
       "      <td>7.4</td>\n",
       "      <td>76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4X0.5CH</td>\n",
       "      <td>4 X0.5</td>\n",
       "      <td>4</td>\n",
       "      <td>0.5</td>\n",
       "      <td>8.0</td>\n",
       "      <td>91</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "           B                    C               D  \\\n",
       "0  Part Code  Cable \\nDescription  No. of \\nCores   \n",
       "1    2X0.5CH               2 X0.5               2   \n",
       "2    3X0.5CH               3 X0.5               3   \n",
       "3    3G0.5CH               3 G0.5               3   \n",
       "4    4X0.5CH               4 X0.5               4   \n",
       "\n",
       "                             E                           F  \\\n",
       "0  Nom. Conductor \\nSize (mm²)  Nom. Cable \\nDiameter (mm)   \n",
       "1                          0.5                         7.1   \n",
       "2                          0.5                         7.4   \n",
       "3                          0.5                         7.4   \n",
       "4                          0.5                         8.0   \n",
       "\n",
       "                             G  \n",
       "0  Nom. Cable \\nWeight (kg/km)  \n",
       "1                           68  \n",
       "2                           76  \n",
       "3                           76  \n",
       "4                           91  "
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "newdf.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "53fd3f8b",
   "metadata": {},
   "outputs": [],
   "source": [
    "list2=list(newdf.loc[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "57a88d3d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Part Code', 'Cable \\nDescription', 'No. of \\nCores', 'Nom. Conductor \\nSize (mm²)', 'Nom. Cable \\nDiameter (mm)', 'Nom. Cable \\nWeight (kg/km)']\n"
     ]
    }
   ],
   "source": [
    "print(list2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "d94f7618",
   "metadata": {},
   "outputs": [],
   "source": [
    "list1.extend(list2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "74501e1e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Conductor Material',\n",
       " 'Insulation Material & \\nColor',\n",
       " 'Braid Armor Material',\n",
       " 'Inner / Out Jacket \\nMaterial',\n",
       " 'Flame Retardancy',\n",
       " 'Oil Resistant',\n",
       " 'Voltage Rating (U0/U)',\n",
       " 'Temperature Range',\n",
       " 'Bending Radius',\n",
       " 'Test Voltage',\n",
       " 'Smoke/ Halogen \\nProperties',\n",
       " 'Other Properties',\n",
       " 'Part Code',\n",
       " 'Cable \\nDescription',\n",
       " 'No. of \\nCores',\n",
       " 'Nom. Conductor \\nSize (mm²)',\n",
       " 'Nom. Cable \\nDiameter (mm)',\n",
       " 'Nom. Cable \\nWeight (kg/km)',\n",
       " 'Part Code',\n",
       " 'Cable \\nDescription',\n",
       " 'No. of \\nCores',\n",
       " 'Nom. Conductor \\nSize (mm²)',\n",
       " 'Nom. Cable \\nDiameter (mm)',\n",
       " 'Nom. Cable \\nWeight (kg/km)']"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "list1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "d0b5955f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Conductor Material', 'Insulation Material & \\nColor', 'Braid Armor Material', 'Inner / Out Jacket \\nMaterial', 'Flame Retardancy', 'Oil Resistant', 'Voltage Rating (U0/U)', 'Temperature Range', 'Bending Radius', 'Test Voltage', 'Smoke/ Halogen \\nProperties', 'Other Properties', 'Part Code', 'Cable \\nDescription', 'No. of \\nCores', 'Nom. Conductor \\nSize (mm²)', 'Nom. Cable \\nDiameter (mm)', 'Nom. Cable \\nWeight (kg/km)', 'Part Code', 'Cable \\nDescription', 'No. of \\nCores', 'Nom. Conductor \\nSize (mm²)', 'Nom. Cable \\nDiameter (mm)', 'Nom. Cable \\nWeight (kg/km)']\n"
     ]
    }
   ],
   "source": [
    "print(list1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "1837eb66",
   "metadata": {},
   "outputs": [],
   "source": [
    "column_header = list1 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "52331c4e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Conductor Material', 'Insulation Material & \\nColor', 'Braid Armor Material', 'Inner / Out Jacket \\nMaterial', 'Flame Retardancy', 'Oil Resistant', 'Voltage Rating (U0/U)', 'Temperature Range', 'Bending Radius', 'Test Voltage', 'Smoke/ Halogen \\nProperties', 'Other Properties', 'Part Code', 'Cable \\nDescription', 'No. of \\nCores', 'Nom. Conductor \\nSize (mm²)', 'Nom. Cable \\nDiameter (mm)', 'Nom. Cable \\nWeight (kg/km)', 'Part Code', 'Cable \\nDescription', 'No. of \\nCores', 'Nom. Conductor \\nSize (mm²)', 'Nom. Cable \\nDiameter (mm)', 'Nom. Cable \\nWeight (kg/km)']\n"
     ]
    }
   ],
   "source": [
    "print(column_header)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e076c2fe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
